# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:12"
      day: "friday"
    open-pull-requests-limit: 25
    labels:
      - "dependencies"
      - "bun"
      - "automated"
    commit-message:
      prefix: "deps(bun)"
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:12"
      day: "friday"
    open-pull-requests-limit: 25
    labels:
      - "dependencies"
      - "go"
      - "automated"
    commit-message:
      prefix: "deps(go)"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:12"
      day: "friday"
    open-pull-requests-limit: 25
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:12"
      day: "friday"
    open-pull-requests-limit: 25
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"
